
package com.mycompany.ues_trans.Vista;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.mycompany.ues_trans.Entidad.Empleado;
import com.mycompany.ues_trans.Modelo.EmpleadoModel;
import java.io.FileOutputStream;
import java.util.List;
//import java.util.Map;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import java.io.File;
import javax.swing.JFileChooser;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.Phrase;

public class JFrameEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form JFrameEmpleado
     */
    
    // Variable global para recordar qué empleado estamos editando  ó eliminando
    private int idSeleccionado = -1;
    
    public JFrameEmpleado() {
                
        initComponents();
        this.setLocationRelativeTo(null); //Inicializa el formulario en el centro de la pantalla
        this.setResizable(false);         //Mantiene el formulario de un solo tamaño
        cargarDatosEnTabla();
    }
    
    //Metodo para cargar los registros en la tabla
    public void cargarDatosEnTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) JTablaEmpleados.getModel();
        modelo.setRowCount(0);

        EmpleadoModel empModel = new EmpleadoModel();
        java.util.List<Empleado> lista = empModel.listar();

        for (Empleado emp : lista) {
            Object[] fila = new Object[6];
            fila[0] = emp.getId();
            fila[1] = emp.getNombre();
            fila[2] = emp.getDepartamento();
            fila[3] = emp.getSalario();
            fila[4] = emp.getBono();
            fila[5] = emp.getSalarioTotal();
            modelo.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cmbDepartamento = new javax.swing.JComboBox<>();
        btnPDF = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaEmpleados = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtBuscarporNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnRestaurar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unidad Transporte UES");
        setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setText("Departamento:");

        jLabel1.setText("Nombre:");

        jLabel3.setText("Salario:");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Actualizar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(29, 29, 29)
                .addComponent(btnEliminar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        cmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrativo", "Motorista" }));
        cmbDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartamentoActionPerformed(evt);
            }
        });

        btnPDF.setText("Generar Reporte PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        jLabel5.setText("Datos del empleado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre)
                                .addComponent(txtSalario)
                                .addComponent(cmbDepartamento, 0, 185, Short.MAX_VALUE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPDF)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        JTablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Departamento", "salario_base", "Bono", "salario_total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTablaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTablaEmpleados);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Buscar por nombre:");

        btnRestaurar.setText("Mostrar Todos");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reporte");

        jMenuItem2.setText("Generar Reporte de costos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarporNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscarporNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)
                            .addComponent(btnRestaurar)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    private void cmbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartamentoActionPerformed

    
    //Boton Nuevo
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        //Este bloque de codigo valida que ningun campo este vacio       
        if (txtNombre.getText().trim().isEmpty() || txtSalario.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, no deje campos vacíos.", "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return; // 
    }
        
        double salarioNuevo = 0;
        try {
        salarioNuevo = Double.parseDouble(txtSalario.getText().trim());
        if (salarioNuevo <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El salario debe ser mayor a cero.", "Dato inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; //Valida que sea mayor que cero
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El salario debe ser un número válido, sin letras.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        return; // Valida que sean estrictamente numeros
    }
        
        //Captura el nombre del formulario
        String nombre = txtNombre.getText();
        String departamento = cmbDepartamento.getSelectedItem().toString();
        
        //Instancia de la clase empleado
        Empleado empleado = new Empleado(nombre, departamento, salarioNuevo);
        
    //Se elige qué método sobrecargado usar según el departamento
    if (departamento.equals("Administrativo")) {
         empleado.CalcularBono(salarioNuevo); // 1 parámetro
    } else if (departamento.equals("Motorista")) {
         empleado.CalcularBono(salarioNuevo, 30); // 2 parámetros (con viáticos fijos equivalente a 30 dolares)
    }

    //Enviamos el objeto empleado a la base de datos a traves del metodo insertar
    //de la clase EmpleadoModel  
    EmpleadoModel empModel = new EmpleadoModel();
    if (empModel.insertar(empleado)) {
        JOptionPane.showMessageDialog(null, "Empleado guardado con éxito.");
        //Aquí llamamos al método para actualizar el JTable
        cargarDatosEnTabla();       
    } else {
        JOptionPane.showMessageDialog(null, "Error al guardar en BD.");
    }
            //Limpiamos los campos
            txtNombre.setText("");
            cmbDepartamento.getItemAt(0);
            txtSalario.setText("");  
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void JTablaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTablaEmpleadosMouseClicked

         int fila = JTablaEmpleados.getSelectedRow();
    
    // Si la fila es válida (mayor o igual a 0)
    if (fila >= 0) {
        //Extraemos el ID (Columna 0) y lo guardamos en nuestra variable global
        idSeleccionado = Integer.parseInt(JTablaEmpleados.getValueAt(fila, 0).toString());
        
        //Extraemos el resto de datos y los ponemos en las cajas de texto de nuestro formulario
        txtNombre.setText(JTablaEmpleados.getValueAt(fila, 1).toString());
        cmbDepartamento.setSelectedItem(JTablaEmpleados.getValueAt(fila, 2).toString());
        txtSalario.setText(JTablaEmpleados.getValueAt(fila, 3).toString());
    }   
            
    }//GEN-LAST:event_JTablaEmpleadosMouseClicked

    //Boton Editar
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      
        //Validamos que el usuario hay selccionado un registro para editarlo
        if (idSeleccionado == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un empleado de la tabla primero.");
        return;
    }
        if (txtNombre.getText().trim().isEmpty() || txtSalario.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, no deje campos vacíos.", "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE); //Validamos que no haya campos vacios
        return; 
    }

    double salarioNuevo = 0;
    try {
        salarioNuevo = Double.parseDouble(txtSalario.getText().trim());
        if (salarioNuevo <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El salario debe ser mayor a cero.", "Dato inválido", javax.swing.JOptionPane.ERROR_MESSAGE); //Valida que sea un numero y mayor que cero 
            return; 
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El salario debe ser un número válido, sin letras.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        return; //Valida que sean numeros
    }

    //Capturamos los datos que están en las cajas de texto (por si el usuario los modificó)
    String nombreNuevo = txtNombre.getText();
    String departamentoNuevo = cmbDepartamento.getSelectedItem().toString();
  
    Empleado empleado = new Empleado(nombreNuevo, departamentoNuevo, salarioNuevo);
    
    //Le mandamos el ID que guardamos en la variable global
    empleado.setId(idSeleccionado); 

    //Volvemos a aplicar la SOBRECARGA para recalcular el bono
    if (departamentoNuevo.equals("Administrativo")) {
        empleado.CalcularBono(salarioNuevo); 
    } else if (departamentoNuevo.equals("Motorista")) {
        empleado.CalcularBono(salarioNuevo, 30.0); 
    }
    
    //Mandamos a actualizar a la BD
    //Actualizamos el registro seleccionado por el usuario
    //A traves del metodo actuzlizar de nuestra clase EmpleadoModel
    EmpleadoModel empModel = new EmpleadoModel();
    if (empModel.actualizar(empleado)) {
        JOptionPane.showMessageDialog(this, "Empleado actualizado con éxito.");
        
        //Recargamos la tabla 
        cargarDatosEnTabla(); 
        
        //Reiniciamos la variable global que nos ayuda a selccionar al usuario
        idSeleccionado = -1; 
        
        //Limpiamos los campos
        txtNombre.setText("");
        txtSalario.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el empleado.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    //Boton Eliminar
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (idSeleccionado == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un empleado de la tabla para eliminar.");
        return; //Verifica que el usuario hay seleccionado un registro
    }

    //Preguntar de forma segura si realmente quiere borrarlo
    int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea eliminar este registro?", 
            "Confirmar Eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.WARNING_MESSAGE);

    //Si el usuario presiona Sí, procedemos a borrar
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        
        //Instanciamos
        EmpleadoModel empModel = new EmpleadoModel();
        
        //Llamamos al método "eliminar" de nuestra clase EmpleadoModel
        //pasándole el ID guardado
        if (empModel.eliminar(idSeleccionado)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente.");
            
            //Refrescamos la tabla
            cargarDatosEnTabla();
            
            //Reiniciamos el ID y limpiamos las cajas de texto
            idSeleccionado = -1;
            txtNombre.setText("");
            txtSalario.setText("");
            cmbDepartamento.setSelectedIndex(0); // Vuelve al primer elemento del combobox
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Hubo un error al intentar eliminar el registro.");
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    //Boton Buscar
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
    //Captura el texto que el usuario quiere buscar
    String textoBuscado = txtBuscarporNombre.getText().trim();
    
    if (textoBuscado.isEmpty()) {
        // Si no escribió nada, asumimos que quiere ver toda la tabla de nuevo
        cargarDatosEnTabla(); 
        javax.swing.JOptionPane.showMessageDialog(this, "Escriba un nombre para buscar.", "Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    //Obtenemos el modelo visual de la tabla y la vaciamos
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) JTablaEmpleados.getModel();
    modelo.setRowCount(0); 
    
    //Llamar al metodo "buscarPorNombre" de nuestra clase EmpleadoModel
    //y obtenemos la lista filtrada
    EmpleadoModel empModel = new EmpleadoModel();
    List<Empleado> listaFiltrada = empModel.buscarPorNombre(textoBuscado);
    
    //Se llena la tabla con los resultados encontrados
    for (Empleado emp : listaFiltrada) {
        Object[] fila = new Object[6];
        fila[0] = emp.getId();
        fila[1] = emp.getNombre();
        fila[2] = emp.getDepartamento();
        fila[3] = emp.getSalario();
        fila[4] = emp.getBono();
        fila[5] = emp.getSalarioTotal();
        
        modelo.addRow(fila);
    }
    
    //Avisamos al usuario si no se encontró a nadie
    if (listaFiltrada.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron empleados con ese nombre.");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    
    //Boton Mostrar Todos
    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        
    //Limpiamos el textbox donde el usuario había escrito
    txtBuscarporNombre.setText("");
    
    //Llamamos al metodo que vuelve a llenar la tabla completa
    cargarDatosEnTabla();
    }//GEN-LAST:event_btnRestaurarActionPerformed

    
    //Boton Generar PDF
    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
    
    //Aca construimos nuestro reporte pdf
    //El reporte debe de mostrar el costo total por departamento
    //Y al final tambien muestra la suma total de ambos
    JFileChooser selector = new JFileChooser();
    selector.setDialogTitle("Guardar Reporte de Planilla");
    selector.setSelectedFile(new File("Reporte_Planilla.pdf"));

    String rutaElegida = "";
    boolean nombreValido = false;

    while (!nombreValido) {
        int respuesta = selector.showSaveDialog(this);

        // Si el usuario presiona "Guardar"
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            rutaElegida = selector.getSelectedFile().getAbsolutePath();
            
            if (!rutaElegida.endsWith(".pdf")) {
                rutaElegida += ".pdf";
            }
            //Creamos un objeto File para verificar si físicamente ya existe en el disco
            File archivoExistente = new File(rutaElegida);

            if (archivoExistente.exists()) {
                //Si ya existe, lanzamos una advertencia al usuario para que decida sobrrescribir o no
                int confirmar = javax.swing.JOptionPane.showConfirmDialog(
                        this,
                        "El archivo ya existe en esta ubicación.\n¿Desea reemplazarlo?",
                        "Confirmar Sobreescritura",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.WARNING_MESSAGE
                );

                if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
                    nombreValido = true; // El usuario acepto sobreescribir el archivo
                }
            } else {
                nombreValido = true; // El archivo no existe, la ruta está libre y es segura
            }
            
        } else {
            return; 
        }
    }
    
    //Instanciamos el documento 
    Document documento = new Document();
    
    try {
        //El usuario define la ruta donde se guardará
        PdfWriter.getInstance(documento, new FileOutputStream(rutaElegida));
        
        //Abrimos el documento para empezar a editar sus carateristicas
        documento.open();
        
        //Le damos estilo a los diferentes titulos y subtitulos  
        Font fuenteTitulo = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, BaseColor.DARK_GRAY);
        Font fuenteSubtitulo = FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.GRAY);
        Font fuenteCabecera = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BaseColor.WHITE);
        
  
        //Este es el titulo y aparecera hasta arriba del documento
        Paragraph titulo = new Paragraph("Reporte de Costos de Planilla\n", fuenteTitulo);
        titulo.setAlignment(1); // Centrado
        documento.add(titulo);
        
        Paragraph subtitulo = new Paragraph("UES-Trans | San Salvador, El Salvador\n\n", fuenteSubtitulo);
        subtitulo.setAlignment(1);
        documento.add(subtitulo);
        
        //Definimos el estilo de la tabla
        PdfPTable tablaPdf = new PdfPTable(2);
        tablaPdf.setWidthPercentage(80); 
        
        //Creamos celdas personalizadas para la cabecera
        PdfPCell celda1 = new PdfPCell(new Phrase("Departamento", fuenteCabecera));
        celda1.setBackgroundColor(new BaseColor(0, 102, 204)); 
        celda1.setHorizontalAlignment(1);
        celda1.setPadding(8); 
        tablaPdf.addCell(celda1);
        
        PdfPCell celda2 = new PdfPCell(new Phrase("Costo Total de Planilla ($)", fuenteCabecera));
        celda2.setBackgroundColor(new BaseColor(0, 102, 204));
        celda2.setHorizontalAlignment(1);
        celda2.setPadding(8);
        tablaPdf.addCell(celda2);
        
        //Lenamos con los datos
        EmpleadoModel empModel = new EmpleadoModel();
        java.util.Map<String, Double> costos = empModel.obtenerCostosPorDepartamento();
        
        double granTotalEmpresa = 0;
        
        for (java.util.Map.Entry<String, Double> entrada : costos.entrySet()) {
            // Creamos celdas normales para alinear el texto de los datos
            PdfPCell celdaDepto = new PdfPCell(new Phrase(entrada.getKey()));
            celdaDepto.setPadding(5);
            tablaPdf.addCell(celdaDepto);
            
            PdfPCell celdaCosto = new PdfPCell(new Phrase(String.format("$ %.2f", entrada.getValue())));
            celdaCosto.setHorizontalAlignment(2);
            celdaCosto.setPadding(5);
            tablaPdf.addCell(celdaCosto);
            
            granTotalEmpresa += entrada.getValue();
        }
        
        documento.add(tablaPdf);
        
        //Destacamos al final el documento el total 
        Font fuenteTotal = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, new BaseColor(204, 0, 0)); // Color Rojo
        Paragraph textoTotal = new Paragraph("\nCosto Total General: $" + String.format("%.2f", granTotalEmpresa), fuenteTotal);
        textoTotal.setAlignment(2); 
        documento.add(textoTotal);
     
        
        //Cerramos y guardamos
        documento.close();
        
        //Le mostramos al usuario que todo salió bien
        javax.swing.JOptionPane.showMessageDialog(this, "¡Reporte generado con éxito en tu Escritorio!", "Reporte Listo", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    } catch (Exception e) {
        // Capturamos cualquier error (si el archivo está abierto y no se puede sobreescribir, o si falta la librería)
        javax.swing.JOptionPane.showMessageDialog(this, "Error al generar el PDF: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnPDFActionPerformed
    
    
    //Opcion Salir de la barra de herramientas
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //Adicionalmente agreamos  la opcion de generar reporte 
    //desde la barra de herramientas clonando el boton para
    //crear el PDF
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       btnPDF.doClick();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablaEmpleados;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JComboBox<String> cmbDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarporNombre;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
